/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchChannelIdRouteImport } from './routes/watch.$channelId'
import { Route as ApiPublicStreamRouteImport } from './routes/api/public/stream'
import { Route as ApiPublicMasterRouteImport } from './routes/api/public/master'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchChannelIdRoute = WatchChannelIdRouteImport.update({
  id: '/watch/$channelId',
  path: '/watch/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStreamRoute = ApiPublicStreamRouteImport.update({
  id: '/api/public/stream',
  path: '/api/public/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMasterRoute = ApiPublicMasterRouteImport.update({
  id: '/api/public/master',
  path: '/api/public/master',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/watch/$channelId': typeof WatchChannelIdRoute
  '/api/public/master': typeof ApiPublicMasterRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/watch/$channelId': typeof WatchChannelIdRoute
  '/api/public/master': typeof ApiPublicMasterRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/watch/$channelId': typeof WatchChannelIdRoute
  '/api/public/master': typeof ApiPublicMasterRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/watch/$channelId'
    | '/api/public/master'
    | '/api/public/stream'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/watch/$channelId' | '/api/public/master' | '/api/public/stream'
  id:
    | '__root__'
    | '/'
    | '/watch/$channelId'
    | '/api/public/master'
    | '/api/public/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WatchChannelIdRoute: typeof WatchChannelIdRoute
  ApiPublicMasterRoute: typeof ApiPublicMasterRoute
  ApiPublicStreamRoute: typeof ApiPublicStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$channelId': {
      id: '/watch/$channelId'
      path: '/watch/$channelId'
      fullPath: '/watch/$channelId'
      preLoaderRoute: typeof WatchChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stream': {
      id: '/api/public/stream'
      path: '/api/public/stream'
      fullPath: '/api/public/stream'
      preLoaderRoute: typeof ApiPublicStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/master': {
      id: '/api/public/master'
      path: '/api/public/master'
      fullPath: '/api/public/master'
      preLoaderRoute: typeof ApiPublicMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WatchChannelIdRoute: WatchChannelIdRoute,
  ApiPublicMasterRoute: ApiPublicMasterRoute,
  ApiPublicStreamRoute: ApiPublicStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
